FROM node:20-alpine

# Definir diretório de trabalho
WORKDIR /app

# Instalar dependências
COPY package.json package-lock.json ./
RUN npm ci

# O restante dos arquivos será montado como volume
# para permitir hot-reload durante o desenvolvimento

# Expor porta 3000 para o servidor de desenvolvimento
EXPOSE 3000

# Comando para iniciar o servidor de desenvolvimento
CMD ["npm", "start"]
